services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: roblox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: new_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=roblox_shop.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  postgres_data:
